# Generated by Django 4.2 on 2023-04-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_posts',
            old_name='steps',
            new_name='steps_to_cook',
        ),
        migrations.AddField(
            model_name='user_posts',
            name='description',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
