# Generated by Django 4.2 on 2023-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_website', '0002_rename_steps_user_posts_steps_to_cook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_posts',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
