# Generated by Django 4.2 on 2023-04-19 14:17

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_website', '0004_rename_user_posts_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='description',
            field=models.TextField(),
        ),
    ]
