# Generated by Django 4.2 on 2023-04-19 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_website', '0011_alter_user_post_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Post',
            new_name='add_recipe',
        ),
    ]
