# Generated by Django 4.2 on 2023-04-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_website', '0012_rename_user_post_add_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_recipe',
            old_name='slug',
            new_name='slu',
        ),
    ]
