# Generated by Django 4.2 on 2023-04-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_website', '0013_rename_slug_add_recipe_slu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_recipe',
            old_name='slu',
            new_name='slug',
        ),
    ]
