# Generated by Django 4.2 on 2023-04-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_website', '0014_rename_slu_add_recipe_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
