# Generated by Django 4.2 on 2023-04-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_website', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
