# Generated by Django 4.2 on 2023-04-22 12:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_website', '0018_alter_add_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
    ]
