# Generated by Django 4.2 on 2023-04-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Entery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Account_info',
        ),
    ]
